/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.recursos.humanos.view;

import com.iudigital.controller.FuncionariosController;
import com.iudigital.dominio.Funcionarios;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenov
 */
public class Main2 extends javax.swing.JFrame {

    private final FuncionariosController funcionariosController;
    private final String[] COLUMNS = {"IDDOC", "TIPODOC", "NOMBRE", "APELLIDOS", "ESTADO CIVIL", "SEXO", "DIRECCIÓN", "TELÉFONO", "FECHANAC"};
    private final static String SELECCIONE = "--SELECCIONE--";

    /**
     * Creates new form Main2
     */
    public Main2() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        funcionariosController = new FuncionariosController();
        listFuncionarios();
        addListener();
    }

    private void listFuncionarios() throws SQLException {
        cbxFuncionarios.removeAllItems();
        Funcionarios funcionarios1 = new Funcionarios();
        funcionarios1.setNombre(SELECCIONE);
        funcionarios1.setIddoc(WIDTH);
        cbxFuncionarios.addItem(funcionarios1);
        tblFuncionarios.removeAll();

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }

        tblFuncionarios.setModel(defaultTableModel);
        try {
            List<Funcionarios> funcionario = funcionariosController.obtenerFuncionarios();
            if (funcionario.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionario.size());
            int row = 0;
            for (Funcionarios funcionarios : funcionario) {
                defaultTableModel.setValueAt(funcionarios.getIddoc(), row, 0);
                defaultTableModel.setValueAt(funcionarios.getTipodoc(), row, 1);
                defaultTableModel.setValueAt(funcionarios.getNombre(), row, 2);
                defaultTableModel.setValueAt(funcionarios.getApellidos(), row, 3);
                defaultTableModel.setValueAt(funcionarios.getEstadocivil(), row, 4);
                defaultTableModel.setValueAt(funcionarios.getSexo(), row, 5);
                defaultTableModel.setValueAt(funcionarios.getDireccion(), row, 6);
                defaultTableModel.setValueAt(funcionarios.getTelefono(), row, 7);
                defaultTableModel.setValueAt(funcionarios.getFechanac(), row, 8);
                row++;

                cbxFuncionarios.addItem(funcionarios);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addListener() {
        cbxFuncionarios.addItemListener(event -> {
            Funcionarios selectedFuncionario = (Funcionarios) event.getItem();
            if (selectedFuncionario.getNombre().equals(SELECCIONE)) {
                txtIdDoc.setText("");
                txtTipoDoc.setText("");
                txtNombre.setText("");
                txtApellidos.setText("");
                txtEstadoCivil.setText("");
                txtSexo.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtFechaNac.setText("");

            } else {
                txtIdDocEdit.setText(String.valueOf(selectedFuncionario.getIddoc()));
                    txtTipoDocEdit.setText(selectedFuncionario.getTipodoc());
                    txtNombreEdit.setText(selectedFuncionario.getNombre());
                    txtApellidosEdit.setText(selectedFuncionario.getApellidos());
                    txtEstadoCivilEdit.setText(selectedFuncionario.getEstadocivil());
                    txtSexoEdit.setText(selectedFuncionario.getSexo());
                    txtDireccionEdit.setText(selectedFuncionario.getDireccion());
                    txtTelefonoEdit.setText(selectedFuncionario.getTelefono());
                    txtFechaNacEdit.setText(String.valueOf(selectedFuncionario.getFechanac()));
            }
            System.out.println("selectedFuncionario = " + selectedFuncionario);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPFuncionarios = new javax.swing.JPanel();
        jPFuncionarios2 = new javax.swing.JPanel();
        lblIdDoc1 = new javax.swing.JLabel();
        lblTipoDoc1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellidos1 = new javax.swing.JLabel();
        lblEstadoCivil1 = new javax.swing.JLabel();
        lblSexo1 = new javax.swing.JLabel();
        lblDireccion1 = new javax.swing.JLabel();
        lblTelefono1 = new javax.swing.JLabel();
        txtIdDoc = new javax.swing.JTextField();
        txtTipoDoc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblFechaNac1 = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPEditar = new javax.swing.JPanel();
        jpEdit = new javax.swing.JPanel();
        lblIdDocEdit = new javax.swing.JLabel();
        lblTipoDocEdit = new javax.swing.JLabel();
        lblNombreEdit = new javax.swing.JLabel();
        lblApellidosEdit = new javax.swing.JLabel();
        lblEstadoCivilEdit = new javax.swing.JLabel();
        lblSexoEdit = new javax.swing.JLabel();
        lblDireccionEdit = new javax.swing.JLabel();
        lblTelefonoEdit = new javax.swing.JLabel();
        txtIdDocEdit = new javax.swing.JTextField();
        txtTipoDocEdit = new javax.swing.JTextField();
        txtNombreEdit = new javax.swing.JTextField();
        txtApellidosEdit = new javax.swing.JTextField();
        txtEstadoCivilEdit = new javax.swing.JTextField();
        txtSexoEdit = new javax.swing.JTextField();
        txtDireccionEdit = new javax.swing.JTextField();
        txtTelefonoEdit = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        lblFechaNacEdit = new javax.swing.JLabel();
        txtFechaNacEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFuncionariosEdit = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Recursos Humanos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 150, 30));

        jPFuncionarios2.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblIdDoc1.setText("Id Doc");

        lblTipoDoc1.setText("Tipo Doc");

        lblNombre1.setText("Nombre");

        lblApellidos1.setText("Apellidos");

        lblEstadoCivil1.setText("Estado Civil");

        lblSexo1.setText("Sexo");

        lblDireccion1.setText("Dirección");

        lblTelefono1.setText("Teléfono");

        txtIdDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDocActionPerformed(evt);
            }
        });

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblFechaNac1.setText("Fecha de Nacimiento");

        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPFuncionarios2Layout = new javax.swing.GroupLayout(jPFuncionarios2);
        jPFuncionarios2.setLayout(jPFuncionarios2Layout);
        jPFuncionarios2Layout.setHorizontalGroup(
            jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdDoc1)
                            .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                                .addComponent(txtIdDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lblTipoDoc1)))
                                .addGap(18, 18, 18)
                                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre1)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidos1))
                        .addGap(18, 18, 18)
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoCivil1)
                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion1)
                            .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnGuardar))
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNac1))
                        .addGap(157, 157, 157))))
        );
        jPFuncionarios2Layout.setVerticalGroup(
            jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarios2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDoc1)
                    .addComponent(lblTipoDoc1)
                    .addComponent(lblApellidos1)
                    .addComponent(lblEstadoCivil1)
                    .addComponent(lblNombre1))
                .addGap(34, 34, 34)
                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo1)
                    .addComponent(lblDireccion1)
                    .addComponent(lblTelefono1)
                    .addComponent(lblFechaNac1))
                .addGap(18, 18, 18)
                .addGroup(jPFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPFuncionariosLayout = new javax.swing.GroupLayout(jPFuncionarios);
        jPFuncionarios.setLayout(jPFuncionariosLayout);
        jPFuncionariosLayout.setHorizontalGroup(
            jPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
            .addComponent(jPFuncionarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, Short.MAX_VALUE)
        );
        jPFuncionariosLayout.setVerticalGroup(
            jPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionariosLayout.createSequentialGroup()
                .addComponent(jPFuncionarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Funcionario", jPFuncionarios);

        jpEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        lblIdDocEdit.setText("Id Doc");

        lblTipoDocEdit.setText("Tipo Doc");

        lblNombreEdit.setText("Nombre");

        lblApellidosEdit.setText("Apellidos");

        lblEstadoCivilEdit.setText("Estado Civil");

        lblSexoEdit.setText("Sexo");

        lblDireccionEdit.setText("Dirección");

        lblTelefonoEdit.setText("Teléfono");

        txtIdDocEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDocEditActionPerformed(evt);
            }
        });

        txtApellidosEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosEditActionPerformed(evt);
            }
        });

        txtDireccionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEditActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblFechaNacEdit.setText("Fecha de Nacimiento");

        txtFechaNacEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Funcionarios");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEditLayout = new javax.swing.GroupLayout(jpEdit);
        jpEdit.setLayout(jpEditLayout);
        jpEditLayout.setHorizontalGroup(
            jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditLayout.createSequentialGroup()
                        .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexoEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionEdit)
                            .addGroup(jpEditLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaNacEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacEdit))
                        .addGap(157, 157, 157))
                    .addGroup(jpEditLayout.createSequentialGroup()
                        .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpEditLayout.createSequentialGroup()
                                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdDocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdDocEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoDocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoDocEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonoEdit)
                                    .addComponent(lblNombreEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidosEdit)))
                            .addGroup(jpEditLayout.createSequentialGroup()
                                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEditLayout.createSequentialGroup()
                                .addComponent(lblEstadoCivilEdit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpEditLayout.createSequentialGroup()
                                .addComponent(txtEstadoCivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jpEditLayout.createSequentialGroup()
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel2))
                    .addGroup(jpEditLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnActualizar)
                        .addGap(51, 51, 51)
                        .addComponent(btnEliminar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpEditLayout.setVerticalGroup(
            jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDocEdit)
                    .addComponent(lblTipoDocEdit)
                    .addComponent(lblNombreEdit)
                    .addComponent(lblApellidosEdit)
                    .addComponent(lblEstadoCivilEdit))
                .addGap(18, 18, 18)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoDocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoEdit)
                    .addComponent(lblDireccionEdit)
                    .addComponent(lblTelefonoEdit)
                    .addComponent(lblFechaNacEdit))
                .addGap(18, 18, 18)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)))
        );

        tblFuncionariosEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Doc", "TIpo Doc", "Nombre", "Apellidos", "Estado Civil", "Sexo", "Dirección", "Teléfono", "FechaNac"
            }
        ));
        jScrollPane3.setViewportView(tblFuncionariosEdit);

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addGroup(jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addComponent(jpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar Funcionario", jPEditar);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEditActionPerformed

    private void txtIdDocEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDocEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDocEditActionPerformed

    private void txtApellidosEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosEditActionPerformed

    private void txtFechaNacEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacEditActionPerformed

    private void txtIdDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDocActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtIdDoc.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Id");
            txtIdDoc.requestFocus();
            return;
        }

        if (txtTipoDoc.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo de documento");
            txtTipoDoc.requestFocus();
            return;
        }

        if (txtNombre.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombre");
            txtNombre.requestFocus();
            return;
        }

        if (txtApellidos.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtApellidos.requestFocus();
            return;
        }

        if (txtEstadoCivil.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Estado Civil");
            txtEstadoCivil.requestFocus();
            return;
        }

        if (txtSexo.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite sexo");
            txtSexo.requestFocus();
            return;
        }

        if (txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite dirección");
            txtDireccion.requestFocus();
            return;
        }

        if (txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite teléfono");
            txtTelefono.requestFocus();
            return;
        }

        if (txtFechaNac.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite fecha de nacimiento");
            txtFechaNac.requestFocus();
            return;
        }

        Funcionarios funcionario = new Funcionarios();
        funcionario.setIddoc(Integer.parseInt (txtIdDoc.getText().trim()));
        funcionario.setTipodoc(txtTipoDoc.getText().trim());
        funcionario.setNombre(txtNombre.getText().trim());
        funcionario.setApellidos(txtApellidos.getText().trim());
        funcionario.setEstadocivil(txtEstadoCivil.getText().trim());
        funcionario.setSexo(txtSexo.getText().trim());
        funcionario.setDireccion(txtDireccion.getText().trim());
        funcionario.setTelefono(txtTelefono.getText().trim());
        funcionario.setFechanac(Date.valueOf (txtFechaNac.getText().trim()));

        try {
            funcionariosController.crearFuncionario(funcionario);
            txtIdDoc.setText("");
            txtTipoDoc.setText("");
            txtNombre.setText("");
            txtApellidos.setText("");
            txtEstadoCivil.setText("");
            txtSexo.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtFechaNac.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario creado con éxito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Funcionario no pudo ser creado");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtIdDocEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar el funcionario de la lista");
            txtIdDocEdit.requestFocus();
            return;
        }

        if (txtTipoDocEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo de documento");
            txtTipoDocEdit.requestFocus();
            return;
        }

        if (txtNombreEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombre");
            txtNombreEdit.requestFocus();
            return;
        }

        if (txtApellidosEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtApellidosEdit.requestFocus();
            return;
        }

        if (txtEstadoCivilEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Estado Civil");
            txtEstadoCivilEdit.requestFocus();
            return;
        }

        if (txtSexoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite sexo");
            txtSexoEdit.requestFocus();
            return;
        }

        if (txtDireccionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite dirección");
            txtDireccionEdit.requestFocus();
            return;
        }

        if (txtTelefonoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite teléfono");
            txtTelefono.requestFocus();
            return;
        }

        if (txtFechaNacEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite fecha de nacimiento");
            txtFechaNacEdit.requestFocus();
            return;
        }
       
        Funcionarios funcionario = new Funcionarios();
        funcionario.setIddoc(Integer.parseInt (txtIdDocEdit.getText().trim()));
        funcionario.setTipodoc(txtTipoDocEdit.getText().trim());
        funcionario.setNombre(txtNombreEdit.getText().trim());
        funcionario.setApellidos(txtApellidosEdit.getText().trim());
        funcionario.setEstadocivil(txtEstadoCivilEdit.getText().trim());
        funcionario.setSexo(txtSexoEdit.getText().trim());
        funcionario.setDireccion(txtDireccionEdit.getText().trim());
        funcionario.setTelefono(txtTelefonoEdit.getText().trim());
        funcionario.setFechanac(Date.valueOf (txtFechaNacEdit.getText().trim()));
      

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar funcionario", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funcionariosController.actualizarFuncionario (funcionario.getIddoc(), funcionario);
                LimpiarTxtEdit();
                listFuncionarios();
                
                JOptionPane.showMessageDialog(null, "Se ha actualizado con éxito");
            }catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fue posible actualizar funcionario");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        if (txtIdDocEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar el funcionario de la lista");
            txtIdDocEdit.requestFocus();
            return;
        }
        
        int opt = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el funcionario","Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funcionariosController.eliminarFuncionario(Integer.parseInt(txtIdDocEdit.getText()));
                LimpiarTxtEdit();
                listFuncionarios();
                
                JOptionPane.showMessageDialog(null, "Se ha eliminado con éxito");
            }catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fue posible eliminar funcionario");
            }
        }        
    }//GEN-LAST:event_btnEliminarActionPerformed
       
        private void LimpiarTxtEdit() {
            txtIdDocEdit.setText("");
                txtTipoDocEdit.setText("");
                txtNombreEdit.setText("");
                txtApellidosEdit.setText("");
                txtEstadoCivilEdit.setText("");
                txtSexoEdit.setText("");
                txtDireccionEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechaNacEdit.setText("");
        }
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main2().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Funcionarios> cbxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPFuncionarios;
    private javax.swing.JPanel jPFuncionarios2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jpEdit;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblApellidosEdit;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblDireccionEdit;
    private javax.swing.JLabel lblEstadoCivil1;
    private javax.swing.JLabel lblEstadoCivilEdit;
    private javax.swing.JLabel lblFechaNac1;
    private javax.swing.JLabel lblFechaNacEdit;
    private javax.swing.JLabel lblIdDoc1;
    private javax.swing.JLabel lblIdDocEdit;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombreEdit;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblSexoEdit;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefonoEdit;
    private javax.swing.JLabel lblTipoDoc1;
    private javax.swing.JLabel lblTipoDocEdit;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTable tblFuncionariosEdit;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosEdit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEdit;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtEstadoCivilEdit;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtFechaNacEdit;
    private javax.swing.JTextField txtIdDoc;
    private javax.swing.JTextField txtIdDocEdit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEdit;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexoEdit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEdit;
    private javax.swing.JTextField txtTipoDoc;
    private javax.swing.JTextField txtTipoDocEdit;
    // End of variables declaration//GEN-END:variables
}
